# Generated by Django 5.0.7 on 2024-08-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name quiz')),
                ('theme', models.CharField(max_length=255, verbose_name='Theme quiz')),
                ('description', models.TextField(verbose_name='Description quiz')),
                ('img', models.ImageField(upload_to=None, verbose_name='ScreenSaver')),
                ('status', models.BooleanField(default=False, verbose_name='Status quiz')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('available_cert', models.BooleanField(default=False, verbose_name='Available certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('media_type', models.CharField(max_length=255, verbose_name='Media type')),
                ('media_name', models.CharField(max_length=255, verbose_name='Media name')),
                ('qs_type', models.CharField(max_length=255, verbose_name='Question type')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizlist')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name team')),
                ('color', models.CharField(max_length=255, verbose_name='Color team')),
                ('team_key', models.CharField(max_length=255, verbose_name='Team key')),
                ('active', models.BooleanField(default=True, verbose_name='Active team')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.quizlist')),
            ],
        ),
        migrations.CreateModel(
            name='QuizArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(null=True, verbose_name='Result quiz')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.quizlist')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct answer')),
                ('time_given', models.DateTimeField(auto_now_add=True, verbose_name='Time given')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizlist')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('time_given', models.DateTimeField(auto_now_add=True, verbose_name='Time given')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
